// import {Datastore} from '@google-cloud/datastore';
// import express from 'express';
// import cors from 'cors'

const {Datastore} = require('@google-cloud/datastore')
const express = require('express')
const cors = require('cors')

const app = express();
app.use(express.json())
app.use(cors())

const datastore = new Datastore()
// Associate {email:"" (unique identifier), fname:"", lname:"", points:0}

app.post('/associates',async (req,res)=>{
    const associate = req.body;
    const key = datastore.key(['Associate',associate.email])// you can specify your OWN ID rather than an autogenerated number id
    const response = await datastore.save({key:key,data:associate})
    res.status(201)
    res.send('Successfully Created a new Associate')
});

// Query params are the typical way of doing filtering in REST apis
app.get('/associates', async (req, res)=>{

    if(req.query.pointsgreater){
        const query = datastore.createQuery('Associate').filter('points','>',Number(req.query.pointsgreater));
        const [data,metaInfo] = await datastore.runQuery(query);
        res.send(data)
    }else{
        const query = datastore.createQuery('Associate');
        const [data,metaInfo] = await datastore.runQuery(query)
        res.send(data)
    }
    
})

app.get('/associates/:email', async (req, res)=>{
    const key = datastore.key(['Associate',req.params.email]);
    const associate = await datastore.get(key);
    res.send(associate)
});

app.listen(3000,()=>console.log('Application started'))