apiVersion: v1
kind: PersistentVolumeClaim # this will survive regardless of what happens to the pod
metadata:
    name: small-persistent-disk
spec: # Technical specifications of the PVC
    accessModes: # Refer to different access modes below
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
# ReadWriteOnce: The volume can be mounted as read-write by a single node.
# ReadOnlyMany: The volume can be mounted read-only by many nodes.
# ReadWriteMany: The volume can be mounted as read-write by many nodes. PersistentVolume resources that are backed by Compute Engine persistent disks don't support this access mode.
