apiVersion: v1
kind: Service # what type of resource we are creating
metadata:
    name: hola-service # Arbitrary name
spec:
    type: ClusterIP # IF you don't specify a type, it would default to ClusterIP
    selector:
        app: hola-er # grab pods with this key value label
    ports:
        - protocol: TCP
          port: 80 # port the load balancer
          targetPort: 3000 # port to access the pod(s) on
